### ISSUE TITLE
deployed but page has an issue

### ISSUE THREAD

**Issue by ng-model** [madurimanoj/ng-book2#26]
![image](https://user-images.githubusercontent.com/11791070/30613148-0157472a-9d55-11e7-934f-1f98966d7993.png)

**Comment by rahulrsingh09** [comment]
You have a problem with your aot build please check .

```
rahul@Rahul-PC:~/Angular/ng-book2$ ng build --prod
 92% recording/home/rahul/Angular/ng-book2/node_modules/extract-text-webpack-plugin/dist/index.js:246
            if (extractedChunk.getNumberOfModules()) {
                               ^

TypeError: extractedChunk.getNumberOfModules is not a function
    at ExtractTextPlugin.<anonymous> (/home/rahul/Angular/ng-book2/node_modules/extract-text-webpack-plugin/dist/index.js:246:32)
    at Array.forEach (native)
    at Compilation.<anonymous> (/home/rahul/Angular/ng-book2/node_modules/extract-text-webpack-plugin/dist/index.js:245:27)
    at Compilation.applyPluginsAsyncSeries (/home/rahul/Angular/ng-book2/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/home/rahul/Angular/ng-book2/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:653:9)
    at next (/home/rahul/Angular/ng-book2/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/home/rahul/Angular/ng-book2/node_modules/@angular/cli/node_modules/webpack/lib/ProgressPlugin.js:111:6)
    at next (/home/rahul/Angular/ng-book2/node_modules/tapable/lib/Tapable.js:204:14)
    at /home/rahul/Angular/ng-book2/node_modules/extract-text-webpack-plugin/dist/index.js:241:13
    at /home/rahul/Angular/ng-book2/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/rahul/Angular/ng-book2/node_modules/async/dist/async.js:998:13)
    at /home/rahul/Angular/ng-book2/node_modules/async/dist/async.js:906:16
    at /home/rahul/Angular/ng-book2/node_modules/extract-text-webpack-plugin/dist/index.js:224:15
    at /home/rahul/Angular/ng-book2/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/rahul/Angular/ng-book2/node_modules/async/dist/async.js:998:13)
    at /home/rahul/Angular/ng-book2/node_modules/async/dist/async.js:906:16
    at /home/rahul/Angular/ng-book2/node_modules/extract-text-webpack-plugin/dist/index.js:213:21
    at rebuilding.forEach.cb (/home/rahul/Angular/ng-book2/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:521:29)
    at Array.forEach (native)
    at callback (/home/rahul/Angular/ng-book2/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:521:15)
    at processModuleDependencies (/home/rahul/Angular/ng-book2/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:540:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I have made it run using dev build check the working link https://madurimanoj.github.io/ng-book2/

**Comment by rahulrsingh09** [comment]
Done

**Comment by ng-model** [comment]
with dev build the problem solved ?
